export enum EventType {
    DISPENSE_SUCCESS = 'DISPENSE_SUCCESS',
    DISPENSE_FAIL = 'DISPENSE_FAIL',
    REFILL = 'REFILL',
    THRESHOLD_ALERT = 'THRESHOLD_ALERT',
    SCHEDULE_EDIT = 'SCHEDULE_EDIT',
    EMERGENCY_OVERRIDE = 'EMERGENCY_OVERRIDE'
}
